### ISSUE TITLE
store color patches in local storage

### ISSUE THREAD

**Issue by surreal6** [surreal6/filmviz#1]
http://www.w3schools.com/html/html5_webstorage.asp

// Store
localStorage.setItem("lastname", "Smith");
// Retrieve
document.getElementById("result").innerHTML = localStorage.getItem("lastname");

**Comment by Roboe** [comment]
Probably we'll want to store JSON data.
Seems like `localStorage` only store strings, and turn every other thing you pass to string.

To store a JSON object:
``` JavaScript
var obj = {
    foo: 'bar'
}
localStorage.setItem('myjson', JSON.stringify(obj));
```

To retrieve a JSON object:
``` JavaScript
var obj = JSON.parse(localStorage.getItem('myjson'));
```
