### ISSUE TITLE
Project .zip Saving/Loading

### ISSUE THREAD

**Issue by surreal6** [surreal6/filmviz#10]
jszip

**Comment by Roboe** [comment]
First step. Writing and exporting one simple VTT file. Needs exporting all the project estructure and some reformatting, but that's simple, I guess.

**Comment by surreal6** [comment]
zip structure:

JSON file including all details from project, currently:

name:
video source:
selected Analysis:

and a subfolder called analysis with:
one webVTT file for each analysis

---------------------
filenames:

project.name.zip
    project.name.JSON
        analysis/project.name.color.vtt
        analysis/project.name.audio.vtt
        analysis/project.name.motion.vtt
        analysis/project.name.metadata1.vtt
        ....
        analysis/project.name.metadataN.vtt

**Comment by Roboe** [comment]
I thought "Selected analysis" wasn't important (because it's an internal variable), but you included it so we can redirect the user to its last "working-on analysis", right?

**Comment by Roboe** [comment]
Should we `slugify` the project name or simply make it the name of the video for easy VTT loading?

**Comment by Roboe** [comment]
Zip saving is [already working](https://github.com/surreal6/filmviz/commit/571ce46e990b468b58903f60cf65fb61dc0233e0) on `master`, ;)

Good night!

**Comment by Roboe** [comment]
Done
