### ISSUE TITLE
local app interface

### ISSUE THREAD

**Issue by surreal6** [surreal6/filmviz#13]
* load and save project files
(project structure)
zip -->
     project.json (with relative paths to all files:)
     vtt/
          color.vtt
          audio.vtt
          rythm.vtt
         ...
          metadata4.vtt
    img/
          thumb0001.jpg
          thumb0002.jpg
          ....
          thumb8653.jpg

* view and edit individual VTT files
* generate limited analysis (from TC to TC)
* Edit individual CUEs

**Comment by Roboe** [comment]
JSZip will help us with this: https://stuk.github.io/jszip/
`npm install jszip --save`

It seems really straightforward
