### ISSUE TITLE
Offline capabilities for long processings

### ISSUE THREAD

**Issue by bertocq** [surreal6/filmviz#8]
Needing internet connection while you are processing a long video could be an issue for some users, even needing connection at the start of the processing. 

Since all is done in the front-end (in the browser), it will be easier to make the app work totally offline (alerting the user when connection goes of and on to upload  the results). One way could be making a firefox/chrome plugin, or just download the code and launch the app in localhost... but both seems too much hassle.

Using the [Cache Manifest](https://en.wikipedia.org/wiki/Cache_manifest_in_HTML5) feature and some tricks with js and localstorage the process would be transparent for the user, and much faster than the other options.

Just read this article and take a peek at the demo http://alistapart.com/article/application-cache-is-a-douchebag

Again, count with my help to develop this suggestion. I would start it after #4 is completed since localstorage would be used for permanent storage of html content, and erasing processing info would require a little more precaution.

**Comment by Roboe** [comment]
Closed for cleanliness.
We may have a look at this when Service Workers (replacement for AppCache) are ready for production.
